### ISSUE TITLE
Using native browser scrollbar

### ISSUE THREAD

**Issue by davidstellini** [davideperozzi/smoovy#10]
Hi!

Great job on an amazing library - I love the structure, the reuse, and the TypeScript :)

I have a question I couldn't figure out from the docs. Is it possible to show the native browser scrollbar? It doesn't seem very happy with setting `overflow-y: scroll` on `smoovy-container`.

**Comment by davideperozzi** [comment]
Hi David!

Thank you :)

A native scrollbar is possible. I created a special configuration for it here: https://github.com/davideperozzi/smoovy/blob/master/packages/scroller/src/scroller.ts#L32-L77
> It should work out of the box after replacing `smoothScroll` with `nativeSmoothScroll`.

Some things you should keep in mind when using the native scrollbar approach: 
- You can't use it for nested scrollable elements. Only for the main viewport. 
- The container will be fixed due this configuration [here](https://github.com/davideperozzi/smoovy/blob/master/packages/scroller/src/scroller.ts#L68-L73). 
- I'm still working on it and testing the usability. For now, things like "scroll to the focus elements" are working fine.
- It's disabled on mobile devices due this setting [here](https://github.com/davideperozzi/smoovy/blob/master/packages/scroller/src/scroller.ts#L49-L52).
- Methods like `scroller.lock()` etc. are not being used by the `nativeSmoothScroll` yet. So locking the scroll position won't work for now.

You can checkout a live example here: https://www.hoepfner-braeu.de/iwerkx/

I hope this solves you problem :) 
Feel free to ask, if you have further questions!

**Comment by davidstellini** [comment]
Thanks :) Worked immediately!
