### ISSUE TITLE
Excluding elements from triggering a recalc()

### ISSUE THREAD

**Issue by davidstellini** [davideperozzi/smoovy#15]
I may be making a few assumptions in the below issue:

I noticed this library hooks up a MutationObserver to the smoovy-container, and listens to all subtree changes to trigger a recalc().

The issue with this is that certain elements or animations might trigger fast updates, triggering a recalc() in the middle of a scroll. This somehow seems to result in the page jumping up and down.

One way to replicate it is using a "Typewriter" animation library, which would update text nodes with a ~200ms frequency. Here's an example:
https://jsfiddle.net/hzfxp2L9/

One way I can propose fixing it, is by supporting a data-smoovy-exclude property.
As soon as the mutation observer triggers the callback, go up the DOM tree, and if a parent is found to contain this property, the chain stops there and it doesn't trigger a recalc.

What do you think? I can put the time to produce a reproducible example or open an MR.

**Comment by davidstellini** [comment]
By the way, this only seems to be happening on newer versions.
"@smoovy/scroller": "0.1.15", - no issue
"@smoovy/scroller": "0.1.16", - no issue
"@smoovy/scroller": "0.1.20", - no issue
"@smoovy/scroller": "0.1.21", - issue replicated

**Comment by davideperozzi** [comment]
@davidstellini Maybe I will add a filter method in the future, but for now you could configure the mutation observer that way: 

```
nativeSmoothScroll({
  observer: {
    throttle: 300,
    mutators: [
      {
        target: document.body,
        options: {
          childList: true,
          subtree: true
        }
      }
    ]
  }
});
```
By default the [`characterData`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/characterData) is beeing used. If you remove it, you should not have any problems with textual changes anymore :)

Does this help you?

**Comment by davidstellini** [comment]
Sorry for the late reply - this worked, however in the end we ended up doing a css only typewriter which fixed it :D
